apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec: 
  volumes:
  - name: pv-volume
    persistentVolumeClaim:
      claimName: app-data-sc
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: pv-volume
