apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: no-privileged
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: podsecuritypolicy
  subjects:
  - kind: ServiceAccount
    name: psp-sa
    namespace: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
