apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: podsecuritypolicy
    namespace: default
  rules:
  - apiGroups:
    - policy
    resourceNames:
    - default
    resources:
    - podsecuritypolicies
    verbs:
    - use
  - apiGroups:
    - extensions
    resourceNames:
    - default
    resources:
    - podsecuritypolicies
    verbs:
    - use
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
