apiVersion: v1
kind: Pod
metadata:
  name: test-sidecar
spec:
  containers:
  - name: input-stream
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      mkdir -p /var/log;
      while true;
      do
        echo "$(date) INFO $i" >> /var/log/sidecar-app.log;
        i=$((i+1));
        sleep 1;
      done
    volumeMounts:
    - name: logs
      mountPath: /var/log
  - name: output-print
    image: busybox
    args: ["/bin/sh", "-c", "tail -n+1 -f /var/log/sidecar-app.log"]
    volumeMounts:
    - name: logs
      mountPath: /var/log
  volumes:
  - name: logs
    emptyDir: {}
