apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: cluster-role-example
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", "create"]

