apiVersion: v1
kind: Pod
metadata:
  labels:
    app: shared-volume
  name: shared-volume
  namespace: default
spec:
  containers:
  - image: index.tenxcloud.com/demo/streaming-app:v1.0
    imagePullPolicy: IfNotPresent
    name: streaming-app
    volumeMounts:
    - mountPath: /var/log
      name: logs
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
    command: ["/bin/sh","-c","tail -f /var/log/test.log"]
    volumeMounts:
    - mountPath: /var/log
      name: logs
  volumes:
  - name: logs
    emptyDir: {}
  
