apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    name: web4
spec:
  containers:
  - name: db1
    image: mysql:5.7
    envFrom:
      - secretRef:
          name: mysecret
    resources:
      limits:
        memory: "300Mi"
        cpu: "200m"
    ports:
      - containerPort: 3306
  - name: test
    image: mahendrshinde/mysql-client:latest
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "echo Hello World && sleep 3600"]
    resources:
      limits:
        memory: "32Mi"
        cpu: "100m"
